apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Database
  - database/configmap.yaml
  - database/pv.yaml
  - database/pvc.yaml
  - database/service.yaml
  - database/statefulset.yaml

  # Backend
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml

  # Frontend
  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml

  # Expose via NodePort for Caddy
  - expose/backend-nodeport.yaml
  - expose/frontend-nodeport.yaml
