apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo-list-demo
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "todolist"
  DATABASE_USER: "todolist"
  PORT: "5000"
  NODE_ENV: "production"
